services:
  - type: web
    name: telegram-gemini-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-bot-db
          property: connectionString

databases:
  - name: telegram-bot-db
    databaseName: telegram_bot
    user: telegram_bot 