services:
  - type: web
    name: telegram-gemini-bot
    env: python
    buildCommand: docker build -t telegram-gemini-bot .
    startCommand: docker run -p $PORT:8000 telegram-gemini-bot
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: APP_URL
        value: https://telegram-gemini-bot.onrender.com
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true
    # Disable auto-sleep
    plan: standard # This specifies a paid plan to avoid sleep
    sleepMode: false # Explicit setting to prevent sleeping
    git add .
    git commit -m "Prepare for Render deployment"
    git push origin main